version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: password
    x-defang-postgres: true

  redis:
    image: redis:6.2
    x-defang-redis: true

  api:
    build:
      context: ./api
    domainname: api.connectier.app
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DATABASE_URL: postgres://user:${POSTGRES_PASSWORD}@postgres:5432/app_db?sslmode=require
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  worker:
    build:
      context: ./api
    command: celery -A config worker -l info
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DATABASE_URL: postgres://user:${POSTGRES_PASSWORD}@postgres:5432/app_db?sslmode=require
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  ui:
    build:
      context: ./ui
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
    domainname: connectier.app
    command: "npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - api

