# Generated by Django 4.2.21 on 2025-05-31 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_update_embedding_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, help_text='Similarity score or ranking value', null=True)),
                ('notes', models.TextField(blank=True, help_text='Summary or explanation of why this match was made', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this match was created')),
                ('context', models.ForeignKey(help_text='The context in which this match was created', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matching.context')),
                ('parent', models.ForeignKey(blank=True, help_text='Reference to a previous version of this match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='matching.match')),
                ('resource', models.ForeignKey(help_text='The entity providing resources or assistance', on_delete=django.db.models.deletion.CASCADE, related_name='resource_matches', to='matching.entity')),
                ('seeker', models.ForeignKey(help_text='The entity seeking resources or assistance', on_delete=django.db.models.deletion.CASCADE, related_name='seeker_matches', to='matching.entity')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of this status update')),
                ('source', models.CharField(choices=[('system', 'System'), ('llm', 'Language Model'), ('human', 'Human')], default='system', help_text='Source of this status update', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this status update was created')),
                ('context', models.ForeignKey(help_text='The context this update relates to', on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='matching.context')),
                ('entities', models.ManyToManyField(blank=True, help_text='Entities involved in this status update', related_name='status_updates', to='matching.entity')),
                ('match', models.ForeignKey(blank=True, help_text='Specific match this update relates to (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='matching.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The content of the feedback')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this feedback was submitted')),
                ('context', models.ForeignKey(help_text='The context this feedback relates to', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='matching.context')),
                ('match', models.ForeignKey(blank=True, help_text='Specific match this feedback relates to (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='matching.match')),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
