# Generated by Django 4.2.21 on 2025-05-24 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='context',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False),
        ),
    ]
