# Generated by Django 4.2.21 on 2025-05-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chunk_id_alter_context_id_alter_document_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('startup', 'Startup'), ('mentor', 'Mentor')], max_length=64),
        ),
    ]
