# Generated by Django 4.2.21 on 2025-05-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_entity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
    ]
