# Generated by Django 4.2.21 on 2025-05-24 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_match_reasoning_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='core.organization'),
        ),
    ]
