# Generated by Django 4.2.21 on 2025-05-25 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_statusupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusupdate',
            name='status_data',
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='task_id',
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='core.context'),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='data',
            field=models.JSONField(help_text='JSON data.', null=True),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='the_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='core.match'),
        ),
    ]
