name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    environment: playground
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Build Docker Compose
      run: docker compose build

    - name: Deploy
      uses: DefangLabs/defang-github-action@v1.2.0